# Generated by Django 4.2.1 on 2023-06-10 13:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('image_link', models.CharField(max_length=30)),
                ('facebook_link', models.CharField(max_length=30)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None), size=None)),
                ('website', models.CharField(max_length=30)),
                ('seeking_venue', models.BooleanField()),
                ('seeking_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('image_link', models.CharField(max_length=30)),
                ('facebook_link', models.CharField(max_length=30)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None), size=None)),
                ('website', models.CharField(max_length=30)),
                ('seeking_talent', models.BooleanField()),
                ('seeking_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.artist')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.venue')),
            ],
        ),
    ]
